FROM rust:alpine AS builder
RUN apk add --no-cache musl-dev
WORKDIR /app
COPY Cargo.toml Cargo.lock build.rs ./
COPY src       ./src
COPY resources ./resources
ARG CARGO_PROFILE=release
ARG CARGO_FEATURES=
RUN cargo build --profile ${CARGO_PROFILE} --features ivf${CARGO_FEATURES:+,$CARGO_FEATURES}

FROM alpine:latest
RUN apk add --no-cache wget
ARG CARGO_PROFILE=release
COPY --from=builder /app/target/${CARGO_PROFILE}/rinha /rinha
EXPOSE 8080
ENTRYPOINT ["/rinha"]
