// Defines the 16-byte packed row layout and the per-query precomputed partial
// distances. The dictionary constants (DICT01 … DICT12) are generated by
// build.rs and injected here at compile time.

// Pull in the dictionary constants produced by build.rs.
include!(concat!(env!("OUT_DIR"), "/dicts.rs"));

pub const SCALE: f32 = 8192.0;

#[inline(always)]
pub fn quantize(v: f32) -> i16 {
    (v * SCALE)
        .round()
        .clamp(i16::MIN as f32, i16::MAX as f32) as i16
}

// 24-bit layout packed into 3 bytes, LSB first:
//   bits  0– 3  (4 bits) : dim 1  index  (installments)
//   bits  4– 8  (5 bits) : dim 3  index  (hour)
//   bits  9–11  (3 bits) : dim 4  index  (dow)
//   bits 12–16  (5 bits) : dim 8  index  (tx_count)
//   bits 17–20  (4 bits) : dim 12 index  (mcc_risk)
//   bit  21     (1 bit)  : dim 9  (is_online)
//   bit  22     (1 bit)  : dim 10 (card_present)
//   bit  23     (1 bit)  : dim 11 (unknown_merchant)
#[inline(always)]
pub fn unpack_bits(packed: &[u8; 3]) -> (usize, usize, usize, usize, usize, u8, u8, u8) {
    let bits = (packed[0] as u32) | ((packed[1] as u32) << 8) | ((packed[2] as u32) << 16);
    (
        (bits & 0xF) as usize,           // dim 1
        ((bits >> 4) & 0x1F) as usize,   // dim 3
        ((bits >> 9) & 0x7) as usize,    // dim 4
        ((bits >> 12) & 0x1F) as usize,  // dim 8
        ((bits >> 17) & 0xF) as usize,   // dim 12
        ((bits >> 21) & 0x1) as u8,      // dim 9  binary
        ((bits >> 22) & 0x1) as u8,      // dim 10 binary
        ((bits >> 23) & 0x1) as u8,      // dim 11 binary
    )
}

/// Precomputed squared distances between a query value and every dictionary entry,
/// for each low-cardinality dimension. Computed once per query (~104 values,
/// ~208 bytes), stays in L1 cache for the entire 100K-row scan. During the scan
/// each lookup is a single array index — no arithmetic.
pub struct PartialDists {
    pub d1:  [u32; 13],
    pub d3:  [u32; 24],
    pub d4:  [u32;  7],
    pub d8:  [u32; 21],
    pub d12: [u32; 10],
    // Query binary dim values (0 or 1) stored alongside so the search loop
    // can compare them against reference bits without re-reading the query.
    pub q9:  u8,
    pub q10: u8,
    pub q11: u8,
}

impl PartialDists {
    pub fn compute(q: &[f32; 14]) -> Self {
        let q1  = quantize(q[1])  as i32;
        let q3  = quantize(q[3])  as i32;
        let q4  = quantize(q[4])  as i32;
        let q8  = quantize(q[8])  as i32;
        let q12 = quantize(q[12]) as i32;

        let mut d1  = [0u32; 13];
        let mut d3  = [0u32; 24];
        let mut d4  = [0u32;  7];
        let mut d8  = [0u32; 21];
        let mut d12 = [0u32; 10];

        for (i, &v) in DICT01.iter().enumerate() {
            let diff = q1 - v as i32;
            d1[i] = (diff * diff) as u32;
        }
        for (i, &v) in DICT03.iter().enumerate() {
            let diff = q3 - v as i32;
            d3[i] = (diff * diff) as u32;
        }
        for (i, &v) in DICT04.iter().enumerate() {
            let diff = q4 - v as i32;
            d4[i] = (diff * diff) as u32;
        }
        for (i, &v) in DICT08.iter().enumerate() {
            let diff = q8 - v as i32;
            d8[i] = (diff * diff) as u32;
        }
        for (i, &v) in DICT12.iter().enumerate() {
            let diff = q12 - v as i32;
            d12[i] = (diff * diff) as u32;
        }

        Self {
            d1, d3, d4, d8, d12,
            q9:  (q[9]  > 0.5) as u8,
            q10: (q[10] > 0.5) as u8,
            q11: (q[11] > 0.5) as u8,
        }
    }
}

/// Pack the 6 continuous dimensions of the query into a 16-byte buffer matching
/// the reference row's first 12 bytes, with two zero i16 padding slots to fill
/// the 128-bit register without contributing to the distance sum.
pub fn query_cont_bytes(q: &[f32; 14]) -> [u8; 16] {
    // Continuous dims: 0, 2, 5, 6, 7, 13 — same order as build.rs.
    let vals = [
        quantize(q[0]),
        quantize(q[2]),
        quantize(q[5]),
        quantize(q[6]),
        quantize(q[7]),
        quantize(q[13]),
        0i16, // padding lane 6 — contributes 0 to distance
        0i16, // padding lane 7 — contributes 0 to distance
    ];
    let mut buf = [0u8; 16];
    for (i, v) in vals.iter().enumerate() {
        buf[i * 2..i * 2 + 2].copy_from_slice(&v.to_ne_bytes());
    }
    buf
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn quantize_known_values() {
        assert_eq!(quantize(0.0), 0);
        assert_eq!(quantize(1.0), 8192);
        assert_eq!(quantize(-1.0), -8192);
        assert_eq!(quantize(0.5), 4096);
    }

    #[test]
    fn unpack_bits_roundtrip() {
        let (i1, i3, i4, i8, i12): (u8, u8, u8, u8, u8) = (5, 10, 3, 15, 7);
        let (b9, b10, b11): (u8, u8, u8) = (1, 0, 1);

        let raw: u32 = (i1 as u32)
            | ((i3  as u32) << 4)
            | ((i4  as u32) << 9)
            | ((i8  as u32) << 12)
            | ((i12 as u32) << 17)
            | ((b9  as u32) << 21)
            | ((b10 as u32) << 22)
            | ((b11 as u32) << 23);
        let packed: [u8; 3] = [raw as u8, (raw >> 8) as u8, (raw >> 16) as u8];

        let (ui1, ui3, ui4, ui8, ui12, ub9, ub10, ub11) = unpack_bits(&packed);
        assert_eq!(ui1,  i1  as usize);
        assert_eq!(ui3,  i3  as usize);
        assert_eq!(ui4,  i4  as usize);
        assert_eq!(ui8,  i8  as usize);
        assert_eq!(ui12, i12 as usize);
        assert_eq!(ub9,  b9);
        assert_eq!(ub10, b10);
        assert_eq!(ub11, b11);
    }

    #[test]
    fn query_cont_bytes_dim0_maps_to_first_i16_slot() {
        // q[0] = 1.0 → quantize = 8192; all other dims = 0.
        // Continuous dims are stored in order: 0, 2, 5, 6, 7, 13.
        // So slot 0 (bytes 0-1) should equal 8192, everything else 0.
        let mut q = [0.0f32; 14];
        q[0] = 1.0;
        let buf = query_cont_bytes(&q);
        assert_eq!(i16::from_ne_bytes([buf[0], buf[1]]), 8192);
        for slot in 1..8 {
            let v = i16::from_ne_bytes([buf[slot * 2], buf[slot * 2 + 1]]);
            assert_eq!(v, 0, "slot {slot} should be zero");
        }
    }

    #[test]
    fn partial_dists_zero_query_has_zero_for_first_dict_entry() {
        // DICT01[0] = quantize(0/12) = 0. When q[1] = 0.0, the squared
        // distance to the first entry must be zero.
        let q = [0.0f32; 14];
        let pd = PartialDists::compute(&q);
        assert_eq!(pd.d1[0], 0);
        assert_eq!(pd.d3[0], 0);
        assert_eq!(pd.d4[0], 0);
        assert_eq!(pd.d8[0], 0);
    }

    #[test]
    fn partial_dists_binary_dims_reflect_query() {
        let mut q = [0.0f32; 14];
        q[9]  = 1.0; // > 0.5 → q9 = 1
        q[10] = 0.0; // ≤ 0.5 → q10 = 0
        q[11] = 1.0; // > 0.5 → q11 = 1
        let pd = PartialDists::compute(&q);
        assert_eq!(pd.q9,  1);
        assert_eq!(pd.q10, 0);
        assert_eq!(pd.q11, 1);
    }
}

/// Pack a normalized f32 vector and its label into the 16-byte row format.
/// Used in tests to build a `FraudIndex` from raw entries without build.rs.
#[cfg(test)]
pub fn pack_row_for_test(v: &[f32; 14], is_fraud: bool) -> [u8; 16] {
    fn find_nearest(dict: &[i16], val: i16) -> usize {
        let mut best_idx = 0;
        let mut best_diff = i32::MAX;
        for (i, &d) in dict.iter().enumerate() {
            let diff = (d as i32 - val as i32).abs();
            if diff < best_diff {
                best_diff = diff;
                best_idx = i;
            }
        }
        best_idx
    }

    let c0  = quantize(v[0]);
    let c2  = quantize(v[2]);
    let c5  = quantize(v[5]);
    let c6  = quantize(v[6]);
    let c7  = quantize(v[7]);
    let c13 = quantize(v[13]);

    let i1  = find_nearest(&DICT01, quantize(v[1]));
    let i3  = find_nearest(&DICT03, quantize(v[3]));
    let i4  = find_nearest(&DICT04, quantize(v[4]));
    let i8  = find_nearest(&DICT08, quantize(v[8]));
    let i12 = find_nearest(&DICT12, quantize(v[12]));

    let b9  = (v[9]  > 0.5) as u8;
    let b10 = (v[10] > 0.5) as u8;
    let b11 = (v[11] > 0.5) as u8;

    let bits: u32 = (i1 as u32)
        | ((i3 as u32) << 4)
        | ((i4 as u32) << 9)
        | ((i8 as u32) << 12)
        | ((i12 as u32) << 17)
        | ((b9 as u32) << 21)
        | ((b10 as u32) << 22)
        | ((b11 as u32) << 23);

    let mut row = [0u8; 16];
    row[0..2].copy_from_slice(&c0.to_ne_bytes());
    row[2..4].copy_from_slice(&c2.to_ne_bytes());
    row[4..6].copy_from_slice(&c5.to_ne_bytes());
    row[6..8].copy_from_slice(&c6.to_ne_bytes());
    row[8..10].copy_from_slice(&c7.to_ne_bytes());
    row[10..12].copy_from_slice(&c13.to_ne_bytes());
    row[12] = bits as u8;
    row[13] = (bits >> 8) as u8;
    row[14] = (bits >> 16) as u8;
    row[15] = is_fraud as u8;
    row
}
